# Generated by Django 2.1.5 on 2021-07-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictrure',
            new_name='picture',
        ),
    ]
